#!/usr/bin/env python3
"""
W0-06A — render the deterministic legacy migration map.

Issue #43 §8 asks for a deterministic plan from the current paths, URLs and
attachments to

    legacy reference -> file_id -> provider location -> relations

This renders that plan as a reviewable document, from the declared sources in
``app.files.migration_map``. It is a PLAN: the script opens no database, reads
no customer file and moves nothing. The worked examples below are produced
from FIXTURE rows that live in this file, so the document can be regenerated
and diffed on any machine without touching a tenant's data.

Two things the document has to make unmissable:

* which rows a migration could actually execute today (none — every source is
  blocked, and each blocker is named), and
* that the same legacy id in two tenants produces two DIFFERENT file ids, which
  is the collision the W0-03E cycles removed and that a careless migration
  would re-create.

    python scripts/w0_06a_migration_plan.py              # write the doc
    python scripts/w0_06a_migration_plan.py --out -      # stdout
    python scripts/w0_06a_migration_plan.py --summary    # counts only
"""
from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import Dict, List, Sequence

BACKEND = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BACKEND / "scripts"))

import w0_06a_file_registry_guard as guard  # noqa: E402

mm = guard._migration
m = guard._models

DOC = BACKEND.parent / "docs" / "architecture" / "W0-06A_MIGRATION_MAP.md"

#: Two tenants holding the SAME legacy ids. The point of the example is the
#: collision, so the fixture is built to collide on every id it can.
FIXTURE_TENANTS = ("BEG", "TCB")

#: One representative row per source, deliberately filled so that each source's
#: own relation logic is exercised. No value here comes from a real tenant.
FIXTURE_ROWS: Dict[str, Dict] = {
    "media_files": {"id": "m-1", "stored_filename": "abc.jpg", "filename": "site.jpg",
                    "url": "/api/media/file/abc.jpg", "context_type": "project",
                    "context_id": "P-1"},
    "project_photos": {"id": "pp-1", "stored_filename": "project_x.jpg",
                       "filename": "wall.jpg", "project_id": "P-1"},
    "scan_docs": {"id": "sd-1", "media_id": "m-1", "file_url": "/api/media/file/abc.jpg",
                  "linked_invoice_id": "I-1", "original_filename": "invoice.pdf"},
    "supplier_invoice_file": {"id": "si-1", "original_file_url": "/api/media/uuid.pdf",
                              "original_file_name": "supplier.pdf", "project_id": "P-1"},
    "missing_smr_attachments": {"id": "ms-1", "attachments": [{"media_id": "m-2"}]},
    "daily_work_log_attachments": {"id": "dl-1", "site_id": "P-1", "attachments": ["m-3"]},
    "change_order_attachments": {"id": "co-1", "attachments": ["m-4"]},
    "pending_expense_receipt": {"id": "pe-1", "media_id": "m-5", "project_id": "P-1"},
    "asset_intake_photo": {"id": "ai-1", "photo_b64": "data:image/jpeg;base64,...",
                           "matched_item_id": "A-1"},
    "asset_item_photo": {"id": "A-1", "photo_url": "data:image/jpeg;base64,..."},
    "user_avatar": {"id": "u-1", "avatar_url": "/api/media/avatar/u1.jpg"},
    "excel_import_templates": {"id": "t-1"},
    "extra_work_photos": {"id": "ew-1", "photos": ["m-6"], "project_id": "P-1"},
    "work_report_photos": {"id": "wr-1", "photos": ["m-7"], "project_id": "P-1"},
    "invoice_scan_pointer": {"id": "I-1", "scan_doc_id": "sd-1"},
    "ocr_intake_media": {"id": "oi-1", "media_id": "m-1"},
}


def fixture_plan() -> List:
    """The plan for one representative row of every source, in both tenants."""
    entries = []
    for org in FIXTURE_TENANTS:
        rows = {key: [dict(row, org_id=org)] for key, row in FIXTURE_ROWS.items()}
        entries.extend(mm.plan_rows(rows))
    return entries


def _row(cells: Sequence[str]) -> str:
    return "| " + " | ".join(str(c).replace("|", "\\|").replace("\n", " ") for c in cells) + " |"


def render() -> str:
    entries = fixture_plan()
    summary = mm.summarise(entries)
    lines: List[str] = []
    add = lines.append

    add("# W0-06A — deterministic legacy migration map")
    add("")
    add("> Generated by `backend/scripts/w0_06a_migration_plan.py`. Do not edit by hand.")
    add("> Task W0-06A / C01, Issue #43 §8, canon FLOW-016.")
    add("")
    add("A **plan**, not a migration. W0-06A moves no customer file, activates no provider")
    add("and deletes nothing. The worked examples below are produced from fixture rows in")
    add("the generator, so this document can be regenerated and diffed anywhere without")
    add("touching a tenant's data.")
    add("")
    add("## 1. The shape")
    add("")
    add("```text")
    add("legacy reference  ->  file_id  ->  provider location  ->  relations")
    add("```")
    add("")
    add("* **legacy reference** — what the row is called today (its id, or the stored URL).")
    add("* **file_id** — derived, not drawn at random:")
    add("  `sha256(org_id | source key | legacy reference)`, truncated to the shape of a")
    add("  freshly minted id. Re-running the plan maps a row to the SAME id, so an")
    add("  interrupted migration resumes and two plans can be diffed; and the owner is")
    add("  INSIDE the hash, so the same legacy id in two tenants never produces one id.")
    add("* **provider location** — `tenants/<org>/files/<prefix>/<file_id><ext>` in the")
    add("  tenant's own provider. Derived from the identity, never the other way round:")
    add("  nothing resolves a file by its object key.")
    add("* **relations** — what the legacy row says the file belongs to.")
    add("")
    add("## 2. Per source")
    add("")
    add(_row(["source", "collection", "action", "blockers that always apply",
              "migration action"]))
    add(_row(["---"] * 5))
    for source in mm.LEGACY_SOURCES:
        add(_row([source.key, "`%s`" % source.collection, source.action,
                  ", ".join(source.standing_blockers) or "—",
                  source.migration_action]))
    add("")

    add("## 3. Worked example — one row per source, in two tenants")
    add("")
    add("Both tenants hold the SAME legacy ids. Note that no two `file_id` values match")
    add("across tenants: the collision cannot survive the derivation.")
    add("")
    add(_row(["source", "tenant", "legacy reference", "file_id", "planned object key",
              "relations", "blockers"]))
    add(_row(["---"] * 7))
    for entry in entries:
        add(_row([
            entry.source_key, entry.org_id or "—", entry.legacy_reference or "—",
            "`%s`" % entry.file_id if entry.file_id else "—",
            "`%s`" % entry.provider_object_key if entry.provider_object_key else "—",
            ", ".join("%s=%s" % (r.relation_type, r.record_id) for r in entry.relations) or "—",
            ", ".join(entry.blockers) or "**none**",
        ]))
    add("")

    add("## 4. Collision check")
    add("")
    add(_row(["source", "legacy reference", "BEG file_id", "TCB file_id", "equal?"]))
    add(_row(["---"] * 5))
    by_key: Dict[str, Dict[str, str]] = {}
    for entry in entries:
        if entry.file_id:
            by_key.setdefault((entry.source_key, entry.legacy_reference), {})[
                entry.org_id] = entry.file_id
    collisions = 0
    for (source_key, reference), ids in sorted(by_key.items()):
        a, b = ids.get("BEG"), ids.get("TCB")
        equal = a is not None and a == b
        collisions += int(equal)
        add(_row([source_key, reference, "`%s`" % a if a else "—",
                  "`%s`" % b if b else "—", "**YES — DEFECT**" if equal else "no"]))
    add("")
    add("Colliding derived ids: **%d** (must be 0)." % collisions)
    add("")

    add("## 5. What a migration could execute today")
    add("")
    add(_row(["metric", "value"]))
    add(_row(["---", "---"]))
    for key in ("entries", "no_content", "executable", "blocked", "relations_planned"):
        add(_row([key, summary[key]]))
    add("")
    add("### Blockers, by reason")
    add("")
    add(_row(["blocker", "rows"]))
    add(_row(["---", "---"]))
    for blocker, count in sorted(summary["by_blocker"].items()):
        add(_row([blocker, count]))
    add("")
    add("`executable` is **%d** out of %d rows that carry content (%d rows have nothing to"
        % (summary["executable"], summary["entries"] - summary["no_content"],
           summary["no_content"]))
    add("migrate at all): nothing in this plan can run in W0-06A.")
    add("Two reasons hold for every row, by construction:")
    add("")
    add("1. no legacy row stores a checksum, so a `REGISTER` row needs its bytes READ —")
    add("   a provider operation this task does not perform;")
    add("2. every `RELATE` / `REPLACE` row points at a file a `REGISTER` row must create")
    add("   first, and none can.")
    add("")
    add("Provider onboarding (a verified Primary Storage Provider per tenant, FLOW-016")
    add("§onboarding gate) is therefore the gate on executing any of this.")
    add("")
    add("## 6. Blockers that need a human answer, not more code")
    add("")
    add("- `%s` — a row with no tenant. W0-03E-A2B backfilled the legacy collections, so"
        % mm.BLOCKER_NO_OWNER)
    add("  this should be empty against real data; it is still checked per row, because a")
    add("  plan that assumed the backfill was complete would migrate an ownerless file into")
    add("  whichever tenant happened to run the job.")
    add("- `%s` — the legacy media context `message` has no collection in the active"
        % mm.BLOCKER_UNMAPPED_CONTEXT)
    add("  backend. A migration cannot invent a business record to attach those files to.")
    add("- `%s` — an attachment stored as an opaque string with no media record behind"
        % mm.BLOCKER_OPAQUE_ATTACHMENT)
    add("  it. Each must resolve to a real media row or be decided on by a human; none is")
    add("  dropped.")
    add("- `%s` — a photo stored as base64 INSIDE a database row. It has no provider"
        % mm.BLOCKER_INLINE_BASE64)
    add("  object at all, so migrating it means WRITING bytes to a provider for the first")
    add("  time, which cannot precede provider onboarding.")
    add("- `%s` — a media row with no context. A human must say what it belongs to."
        % mm.BLOCKER_NO_RELATION)
    add("")
    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv: Sequence[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    parser.add_argument("--out", default=str(DOC), help="output path, or - for stdout")
    parser.add_argument("--summary", action="store_true", help="print counts only")
    args = parser.parse_args(list(argv))

    entries = fixture_plan()
    summary = mm.summarise(entries)
    if args.summary:
        print("W0-06A migration plan: %(entries)d entry(ies), %(no_content)d with no content, "
              "%(executable)d executable, %(blocked)d blocked, "
              "%(relations_planned)d relation(s) planned" % summary)
        for blocker, count in sorted(summary["by_blocker"].items()):
            print("  %-40s %d" % (blocker, count))
        return 0

    text = render()
    if args.out == "-":
        sys.stdout.write(text)
    else:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")
        print("wrote %s (%d entries, %d executable)"
              % (out, summary["entries"], summary["executable"]))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
