#!/usr/bin/env python3
"""
W0-03E-A2B — generate the ownership inventory (docs/architecture/W0-03E-A2B_INVENTORY.md).

Generated, not hand-written, so it cannot drift from the code:

* §1 the protected ownership scope — every collection class of
  ``app.tenancy.ownership`` with its Issue #38 family, tenant key, migration
  action and the application WRITER PATHS that can create its documents
  (``file:line``), found by the same AST resolution the ``A2B-WRITER`` guard uses;
* §2 the dry-run figures ``collection | total | already tenant-bound | ownerless
  | conflicting | platform | action`` from a dry-run report or the real-Mongo
  gate's evidence JSON (``--report``);
* §3 the residual debt: every raw-handle read/write of a tenant-owned
  collection in the application whose filter carries no literal tenant key,
  OUTSIDE the W0-03E protected surface (contract §6 left those modules out of
  W0-03E). Listed, never hidden.

Pure AST + the optional JSON; no database, no application import.

    python scripts/w0_03e_a2b_inventory.py [--report evidence.json] [--out FILE]
"""
import argparse
import ast
import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import w0_03e_a1_tenant_access_guard as guard  # noqa: E402

BACKEND = guard.BACKEND
DOC = BACKEND.parent / "docs" / "architecture" / "W0-03E-A2B_INVENTORY.md"
READS = frozenset({"find", "find_one", "count_documents", "distinct", "aggregate"})
WRITES = frozenset({"update_one", "update_many", "delete_one", "delete_many",
                    "find_one_and_update", "find_one_and_delete", "find_one_and_replace",
                    "replace_one"})


def _calls():
    """(rel, line, collection, method, filter-proven) for every resolvable raw call."""
    own = guard._ownership_module()
    scoped = frozenset(own.ORG_KEYED)
    out = []
    for rel in guard.writer_files():
        tree = ast.parse((BACKEND / rel).read_text(encoding="utf-8"))
        checker = guard._WriterChecker(rel, tree, scoped)
        for fn in ast.walk(tree):
            if not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            aliases = {}
            for call in ast.walk(fn):
                if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute)):
                    continue
                coll = checker._collection(call.func.value, aliases)
                if coll is None:
                    continue
                method = call.func.attr
                if method == "aggregate":
                    proven = guard._pipeline_scoped(guard._arg(call, 0, "pipeline"))
                else:
                    flt = guard._arg(call, 1 if method == "distinct" else 0, "filter")
                    proven = guard._dict_has_tenant(flt)
                upsert = any(kw.arg == "upsert" and isinstance(kw.value, ast.Constant)
                             and kw.value.value is True for kw in call.keywords)
                out.append((rel, call.lineno, coll, method + ("+upsert" if upsert else ""),
                            proven, fn.name))
    return own, sorted(set(out))


def build(report=None) -> str:
    own, calls = _calls()
    creators = defaultdict(list)
    for rel, line, coll, method, _p, _fn in calls:
        if method in guard.CREATE_METHODS or method.endswith("+upsert"):
            creators[coll].append("%s:%d" % (rel, line))
    rows = (report or {}).get("rows") or []
    by_name = {r["collection"]: r for r in rows}
    lines = [
        "# W0-03E-A2B — tenant ownership inventory (generated)",
        "",
        "> Generated by `backend/scripts/w0_03e_a2b_inventory.py` — do not edit by hand.",
        "> Classification source: `backend/app/tenancy/ownership.py` (one list for the "
        "backfill, the dry run, the guard and the tests).",
        "",
        "## 1. Protected ownership scope and writer paths",
        "",
        "Every org-keyed collection is backfilled to the resolved tenant when ownerless "
        "(`BACKFILL_TO_RESOLVED_TENANT`), blocks the whole migration when any row carries "
        "a conflicting owner (`BLOCKED_CONFLICTING_OWNER`), and after the backfill gets the "
        "server-side ownership validator. Writer paths are the application calls that can "
        "CREATE a document (insert / replace); every one of them is proven by the "
        "`A2B-WRITER` guard to stamp `org_id`, or goes through a `TenantData` view that "
        "stamps it. `(TenantData / none)` means only tenant-view writers, or no application "
        "writer at all (legacy-only data).",
        "",
        "| collection | family | key | migration action | creating writer paths |",
        "|---|---|---|---|---|",
    ]
    for coll in sorted(own.ORG_KEYED):
        paths = creators.get(coll) or ["(TenantData / none)"]
        lines.append("| `%s` | %s | `org_id` | BACKFILL_TO_RESOLVED_TENANT / BLOCK on conflict "
                     "| %s |" % (coll, own.ORG_KEYED[coll], "<br>".join(paths)))
    lines += [
        "| `md_*`, `audit_events`, `audit_idempotency`, `audit_counters` | W0-03 Master Data / "
        "W0-04 audit | `tenant_id` | never backfilled; an ownerless row BLOCKS | repository / "
        "store (require tenant_id) |",
        "| `organizations` | tenant root | `id` | inventoried; a second operating org BLOCKS | "
        "`app/tenancy/onboarding.py` |",
        "| `md_uniqueness_runs` | technical | — | none | index bootstrap ledger |",
        "| *any other collection* | UNCLASSIFIED | — | BLOCKS when it holds documents | — |",
        "",
        "## 2. Dry-run figures",
        "",
    ]
    if rows:
        lines += [
            "Source: %s. The real BEG database was NOT read (no production access is "
            "authorized); these are the figures of the synthetic legacy dataset of the "
            "disposable gate, which puts all three ownerless forms (missing / `null` / `\"\"`) "
            "into every org-keyed collection." % (report.get("_source") or "dry-run report"),
            "",
            "| collection | family | total | already tenant-bound | ownerless | conflicting | "
            "platform | migration action |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for r in sorted(rows, key=lambda r: r["collection"]):
            lines.append("| `%s` | %s | %d | %d | %d | %d | %d | %s |" % (
                r["collection"], r["family"], r["total"], r["bound"], r["ownerless"],
                r["conflicting"], r["platform"], r["action"]))
        t = report.get("totals") or {}
        if t:
            lines += ["", "Totals: %s" % ", ".join("%s=%s" % kv for kv in sorted(t.items()))]
    else:
        lines.append("_No report given (`--report`)._")
    protected = set(guard.PROTECTED_MODULES) | set(guard.HELPER_MODULES)
    residual = [c for c in calls if not c[4] and c[3].replace("+upsert", "") in READS | WRITES
                and c[2] in own.ORG_KEYED and c[0] not in protected and c[0].startswith("app/")]
    per_module = defaultdict(lambda: [0, 0])
    for rel, _l, _c, method, _p, _fn in residual:
        per_module[rel][0 if method in READS else 1] += 1
    lines += [
        "",
        "## 3. Residual debt — raw tenant-owned access without a literal tenant filter",
        "",
        "Outside the W0-03E protected surface (W0-03 contract §6 kept these modules out of "
        "W0-03E). Under colliding ids these are cross-tenant reads/writes. The routes on the "
        "Issue #38 matrix (project/team, finance, offers, reports, payments, Master/legacy "
        "reads, warehouses, items) were fixed where the matrix exercises them; the rest is "
        "listed here as debt for the decision that authorizes a REAL second tenant. "
        "Reads: %d, writes: %d." % (
            sum(1 for r in residual if r[3] in READS),
            sum(1 for r in residual if r[3] not in READS)),
        "",
        "| module | unscoped reads | unscoped writes |",
        "|---|---|---|",
    ]
    for rel in sorted(per_module):
        r, w = per_module[rel]
        lines.append("| `%s` | %d | %d |" % (rel, r, w))
    lines += ["", "<details><summary>Every site (file:line collection.method in function)</summary>",
              "", "```"]
    for rel, line, coll, method, _p, fn in residual:
        lines.append("%s:%d %s.%s in %s()" % (rel, line, coll, method, fn))
    lines += ["```", "", "</details>", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--report", default="")
    p.add_argument("--out", default=str(DOC))
    args = p.parse_args(argv)
    report = None
    if args.report:
        data = json.loads(Path(args.report).read_text(encoding="utf-8"))
        report = data.get("dry_run", data)
        report["_source"] = "the real-MongoDB A2B gate evidence (CLI dry run)"
    Path(args.out).write_text(build(report), encoding="utf-8")
    print("written: %s" % args.out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
